### ISSUE TITLE
SukkitX Start-up Bug

### ISSUE THREAD

**Issue by ImDaRealAni** [SukkitX/Sukkit#1]
When I tried running the start.cmd Batch file, it automatically prompted me to download the PocketMine-MP software. 

How to reproduce:

Download the 1.0 release with Git BASH: `git clone --recursive https://github.com/SukkitX/Sukkit.git`

Wait for the software to fully be cloned.

Next build the project into a Java Archive (.jar). I personally do this by creating artifacts with IntelliJ Ultimate but if you can find an archiver to do it instead, you can use that.

Then, with Git BASH, run this command: `./run.cmd` 

This is the problem the software runs into: 

`[CRITICAL] Sukkit has detected a problem with your current installation. The software will attemp to fix this.
[NOTICE] Press enter to continue with the automatic fix...
`

Then, it automatically downloads PHP binaries as well as the PocketMine-MP.phar server software. 

After you attempt running the start.cmd Batch file, you get the PocketMine-MP software starting up and running.

Hopefully this bug will be fixed soon.

**Comment by HGKApps** [comment]
please read the issue guidelines, you know where to find it

rule g374:
Please do not spell Startup with a dash, as it makes reading issues impossible
